version: "2"

services:
  php_apache:
    build: ./build/php_apache
    container_name: php_apache
    volumes:
      - ./src:/var/www/html
    links:
      - mysql
    ports:
      - 80:80

  mysql:
    build: ./build/mysql
    container_name: mysql
    volumes:
      - ./tmp/mysql:/var/lib/mysql
      - ./build/mysql:/docker-entrypoint-initdb.d/
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ROOT_PASSWORD=password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
      - mysql:db
    ports:
      - 8080:80
